# Generated by Django 4.2.3 on 2023-07-07 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopList',
            new_name='Items',
        ),
    ]
