# Generated by Django 4.2.3 on 2023-07-11 11:19

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_rename_shoplist_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='photo',
            field=models.ImageField(upload_to=items.models.upload_to, verbose_name='Фото'),
        ),
    ]
